### ISSUE TITLE
can i use the same library in scala

### ISSUE THREAD

**Issue by mahipalreddyv** [julioasotodv/spark-df-profiling#8]
Hi 
i am trying to use this implement in the Scala note books and is it possible

**Comment by julioasotodv** [comment]
Not for the time being... Although all the statistics gathering is Scala code under the hood, the logic is implemented in PySpark.

In order to do so, the whole library would have to be written in Scala from scratch, and figure out some way to create the plots and html rendering using Scala libraries.
